http:
  port: 9090
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  data:
    host: '*'
    paths: 
      - /api/v1/products/*
      - /api/v1/references/*
      - /api/v1/vendors/*
      - /api/v1/vulnerabilities/*
      - /api/v1/weaknesses/*
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
serviceEndpoints:
  data:
    url: "http://localhost:8081"
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - data
    policies:
      -
        proxy:
          -
            action:
              serviceEndpoint: data
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines